### ISSUE TITLE
Suggestion: Reboot and Autoremoval

### ISSUE THREAD

**Issue by ghost** [Botspot/update-buddy#1]
I enjoy updating my operating system with Update Buddy, as it helps me keep up with the latest versions of Debian. However, I have some suggestions that could be pretty useful.
Many updates require reboots or restarts, like your Pi Apps accessory, so there can be an option to reboot your system after updating.
```
if zenity —question —title=“Updates Complete” —text=“Updates complete. Would you like to reboot the system?” —width=300
then
	reboot
fi
```
You can also add a dialog telling the user that some packages can be removed as they are no longer needed.
Yes, I did install this with Pi Apps.

**Comment by Botspot** [comment]
> I enjoy updating my operating system with Update Buddy, as it helps me keep up with the latest versions of Debian.

Thank you! Yes I think Update Buddy is very useful, but under-appreciated. (the little "All is Well" app has more installs than Update Buddy, which perplexes me often because Update Buddy is so much more useful IMHO.)

> Many updates require reboots or restarts

They do? I almost never reboot after updating. Most updates are for specific apps, like for an IDE, rpi-imager, piclone, libreoffice. 
The only updates that require a reboot to apply would be kernel/firmware updates.

> Many updates require reboots or restarts, like your Pi Apps accessory

This is new to me... When does Pi-Apps ask you to reboot after updating? Were you thinking of the Twister OS patcher?

Anyhow, your idea for displaying a "Reboot?" dialog is not a bad one. I'm just not convinced that enough people would use it for it to be worth the annoyance for everyone else.

**Comment by ghost** [comment]
> > I enjoy updating my operating system with Update Buddy, as it helps me keep up with the latest versions of Debian.
> 
> Thank you! Yes I think Update Buddy is very useful, but under-appreciated. (the little "All is Well" app has more installs than Update Buddy, which perplexes me often because Update Buddy is so much more useful IMHO.)
> 
> > Many updates require reboots or restarts
> 
> They do? I almost never reboot after updating. Most updates are for specific apps, like for an IDE, rpi-imager, piclone, libreoffice.
> The only updates that require a reboot to apply would be kernel/firmware updates.
> 
> > Many updates require reboots or restarts, like your Pi Apps accessory
> 
> This is new to me... When does Pi-Apps ask you to reboot after updating? Were you thinking of the Twister OS patcher?
> 
> Anyhow, your idea for displaying a "Reboot?" dialog is not a bad one. I'm just not convinced that enough people would use it for it to be worth the annoyance for everyone else.

What I meant to say was, Pi Apps needs to restart (all instances need to be closed) for the updates to apply.
Sometimes, ```sudo apt full-upgrade``` updates your Debian distro as well.

**Comment by ghost** [comment]
Suggested features don’t always have to come in.
